language: node_js
node_js:
- '6'
- 6.2.0
- '4'
- 4.4.5
notifications:
  email:
    on_success: change
    on_failure: always
cache:
  directories:
  - node_modules
before_install:
- npm install -g npm@3.8.9
after_script:
- npm run coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- "./node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info"
env:
  global:
  - secure: KKnkaJ/GvIDy3DGj7aiJsxmzcXia28+AYK2D3dgNojaULlDILcD9s8RtivKWbCDCYkp+tOB5KgbLkQQcM+G2/XMOCRDT2fE47MR2mmugREtXpRcEojZ49nb+is+M5LGYpyA5e8fJJvVUESESO2fZV8PVM3EOJTLoD4BUxmd6MpfAvrLKWah7A5XD/RyfzOI+X17PC7rMMrUmYpOJAWC2GGxVakfmJzTJoMEZhvBO98kWvKV0qGQoogK14sX/8cNkRvDdtZ4ZuJxxEEpNFTxEEgE02lRvCiz2/a7zEI0Z69LlYP3+ESDHshcVGGm/5v2wWOvv01qS9l3LEwrc6AioULZfMa6wablUwypdl5NlYyKUtNUj0OZ4R4hyG/VIK4z6Kd0xaCmEwU+knnYTiIP0H5ioefLrm15x4uWk6cjLst8W1ADvu/ZOkFXT4dfb25ywBlCPgQqOArRc3IV7ZKPSekYNpXI+5mj1nh5/2oOkoKxngRjxrmYxlD4xPezzwEd7eor4huttSK5kBL/92GmESFdBrRM+IBuK+BZwTMmLPvxBrwRALhUn1awOU2zstxdOESDiDnICD2/rHSaXG9jIcoypMDnThrpK0XPI5xI1FQGg+OIhfDoduU8eXunpAciVSEtInx93StGnuBfhkNXJYFDdANior/QrRog44WAGjxk=
  - secure: P3ccU889avcj3hNvWi80PFyd91OgcecJsq2evAu8lOiZagzbTeDSe1E/WjHpWt5nqs0dLyPTgpclye+vHok4w+Nih9mLFA5jlPsB1EaCB9OjCwPqQCCF67VfL9rn5OoHAbiYIBlMRt1z8S7Ov/8PgcEs/8ZVGbIAKMmmvAqfgGZhHuvaDyW8dy49dOsTUyb3E41W6LJ94gQrfXxAaKkrpOTHuC+XdiUxXgDkVxITc72GsISRtL/415DbSk394XPc8Wn1ewt0WxlwwhOUoJJ9tyu0jNtn1iE6aqGcPDNQy/9R8pruPoBNz3i8Txhq39ss+26M9gvyI/Z7L2Rl4QL5ccJZIdGiywhGgO6sQ37hf5LcTOf2Fcs/E8DvhhwR+XcMSTHPU3CbV8P+xoJairJww5vroE5u1ohk6oPhLWJM3JOwIjRjpA4RVQSoNHtjXK6XZJReD0x5CkS24F+D4Nohvb5DEzKnkOiC+QruPWEK1kfkOl5qPuI+M1VMGk/BerEPSHnNFTY4DMMzF04+B5WFlwE9sidSxZZhG257Gi6R55uWv05Sca4v9XX3+9fZDGYiJI888QOb4wiHmS8w2e7SY3E30fjCYDUJ2N2AJcWpgKEb3e0Vr59FlzeE+PBCnX5YJh37ybK5UtNvqhKcEDDCwoPiNQtyHBYvPv5PC/HICbk=
