language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- codecov
env:
  global:
  - secure: nPw3U1ckvQjkPzKrT0vErlLxCfBWjAUXnunO4LDNTl20cD4wkHY9RzlyScJsHAQFxAIp+bVoVx92iQ0TT4Lzkwq0FE11W666Kk2sQJHvg1OW+WtnqQEXOkprBH11F0QD9z4UiTVVi7sluERcmrrkfWNle4Q2xWJ+cgEVSAIG9zriA0aUIWl/xvAfJJ1gw/E3nDRxC675sKfiLyprgtQLENh25OgwHha3XzIWJScTvYaz1q2dEJ+meBaQZWwJ9Dh0kl310CO1uF7DQJ5dDpI1f+6YcAvT5gnAOeCt8+bwK5UrhWTnQAiQHiknM4aPMZlk6E7rF4GCWup/BUtHVY+PzT75ji7NvEYyer5woqVu6e7JKsVEhFbP2iYyzR7V6X5Pj8zPVEzSqFu8H3cjLRIze/0wBuMOh8SG/Yyk1u6ZmEtbCWgZfVM9IGHMFeOBHG88jZwcEgdXR5u+DJ3O51Z22C9n76G96O15qhmezwrdGYXyZYnrauLw7oQYixbyuYuaZpwGPcoofDG6y+Ma14s0XffYv/evbXCXahudpJskkyMVTxUjobsCBOrjIPOElTaMaN+jVkDAzKxdkJ0GwIcN61b0vF81paMn5OxLm5epXBzgXMETXd/u2gaonqIKYtaeYgwn/jU+WrAmhmRLMWgGd8tqz0RQnWyTK8ubr2nAQAU=
