language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: c4cknmeWcKqHTBsZ8hFRelttHv4nG7mduX+tn5IS15K9OjOdK9qUWNhFxKtRv0Le6pJcaC98rTmz5y2EGvT5nw+MgK/FIRBN8Y4pJ0M1I2lBKVsYlDmipfe7lbeDS4Uow+s/tqHdhmv2IEDIoktkWDLUT3Pr6c7M4ytSSgzNsH8KeDgUh80aXZWPGMIJaNiFSY1hzxbDNzNTVEkroiSkWb5BB98fJepSQIUlLjsq20pqgpd16h4Gu38vs1nFLtvVMYBXlQkRjBwrXF1L+IN2aMdDNTaRiYFT05beooCJKQ2bUsaze5RAqx9uNS0ikDkhSx9R5ZAqvkOFp/Y0L57cl/3ODGFgg5/GSTdK7h+THriIB2c/0cQkjDfnn1e7E2G7r6UNoWrXwC3/AwE/mwm3Jm9y4+q6sJgNetL9zVk60dZR3DH1evvCQzty40HVi42ACrP787WIPOWRJhMUxJO9+BRS/A5Ae4V1s93fbEa87qK0Fgaz9W1xQYATj2esAoiFPQFW8a0mVcxzgu6fVKwrUNTSrJvluPLkl2q5Nxok1MAsjsoxngbGsFNZZ2DVkjgV/buISV1Xop4eL/rlxlaLOLaIBKu33Ux1C8KktY9Ty/7F9GPHYr8g2jctCUobMEmftNYFFyckoAfVDgovfz/9MHwQB1DZxKB745VTiheYIZQ=
